version: '3.3'
services:
  mongo:
    image: 'mongo:latest'
    container_name: 'mongo'
    ports:
      - '27017:27017'
  account:
    container_name: 'account'
    build: './account'
    ports:
      - '8080:8080'
    depends_on:
      - 'mongo'
